# Generated by Django 3.2 on 2023-11-23 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20231121_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.CharField(default='default', max_length=32, verbose_name='图片'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='user_id',
            field=models.ForeignKey(default='default', on_delete=django.db.models.deletion.CASCADE, to='app.user'),
        ),
    ]
