# Generated by Django 4.2.3 on 2023-11-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_comment_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bangumi",
            name="bangumi_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="blog_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="character",
            name="character_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_id",
            field=models.AutoField(
                primary_key=True, serialize=False, verbose_name="id"
            ),
        ),
    ]
