# Generated by Django 3.2 on 2023-11-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_bangumi_bangumi_id_alter_blog_blog_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bangumi',
            name='image',
            field=models.CharField(default='default', max_length=32, verbose_name='图片'),
            preserve_default=False,
        ),
    ]
